layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6 
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
    behance: thomasmcgonagle
    dribbble: mcgonagletom
    facebook: thomas.mcgonagle
    hackerrank: mcgonagle
    instagram: mcgonagletom
    keybase: mcgonagle
    linkedin: thomasmcgonagle
    mastodon: mcgonagle
    medium: mcgonagle
    stackoverflow: 4716909
    telegram: mcgonagle
    twitter: mcgonagle
  # unsplash: your_username
  # vk: your_username
    website: https://shakeuplabs.com
    youtube: ThomasAMcGonagle

topics:
  - name: DevOps

  - name: SoftOps

  - name: DX

  - name: Developer Productivity (DP)

  - name: CI

  - name: CD
